### PR TITLE
Feature/import exisiting profiles

### PR DESCRIPTION
**Pull request by adku**
Implemented feature request: https://github.com/jamf/PPPC-Utility/issues/3

Even more there is possibility to import signed profiles.

Right now I tested it only with profiles generated via PPC-Utility, not sure if there is support for TCC profiles from other apps.

### CODE REVIEW

**Comment by watkyn** [comment]
@adku I tried importing a profile from Rich Trouton's GitHub account where he has some various ones for specific workflows:
https://github.com/rtrouton/privacy_preferences_control_profiles/blob/master/Privacy%20Settings%20Whitelist%20-%20Microsoft/Microsoft%20Outlook/Unsigned/Microsoft_Outlook_and_Skype_for_Business_Notifications_v1.mobileconfig
This one for instance, gives an error about "Invalid TCC Profile. Please make sure that required keys are inside profile: payloadScope". 

I think we'll want to make sure most of the ones people share like this would work to import.

**Comment by watkyn** [comment]
Looks like this line just needs a capital "P" and it should fix the issue:
        case scope = "payloadScope"
Line 106 TCCProfile.swift.

Using some of the examples from https://github.com/rtrouton/privacy_preferences_control_profiles/ in the unit tests would be nice.

**Comment by adku** [comment]
@watkyn Thanks a lot, I'll try to fix it :)

**Comment by watkyn** [comment]
Closing this PR as we have moved it to the main jamf repo for some further tweaking. Thanks @adku for the work!

**Pull request closed without merging**
