### PR TITLE
113 connection to jamf pro should be updated to use bearer tokens

### LINKED ISSUE #113: Connection to Jamf Pro should be updated to use Bearer Tokens
Jamf Pro v10.35+ supports bearer tokens for access to the endpoints that PPPC Utility uses.  We need to update the networking code to support this newer standard.  More info can be [found here](https://developer.jamf.com/jamf-pro/docs/classic-api-authentication-changes).

An important note in the linked document says
> Support for Basic authentication via the Classic API has been deprecated and will be removed at a future time (estimated removal date: August-December 2022).

Another important factor is that the PPPC Utility should try to be backwards compatible.   Using bearer tokens should be the new default, but the app should have an option to support Jamf Pro v10.34 and lower with Basic Authentication.

### PR DESCRIPTION
**Pull request by macblazer**
Refactored some of the code around the networking, such as making a `SemanticVersion` type and moving the configuration profile API payload generation out of the networking code and over to the `TCCProfile` type.

Using async-await style network connections, and using an `actor` to synchronize getting/refreshing a bearer token.

Fixes #113

### CODE REVIEW

**Comment by macblazer** [comment]
If anybody can tell me what exactly SwiftLint is complaining about with the 6 `orphaned_doc_comment` errors I would be happy to fix it.  The errors in GitHub action log don't have line numbers or even filenames associated with them, and locally SwiftLint v0.47.1 is happy with the code.

**Comment by macblazer** [comment]
I updated the GitHub action that runs SwiftLint to the latest version, modified a couple of comments in the code, and now it's happy.

**Review by watkyn — CHANGES_REQUESTED** [review]
@macblazer nice to see the async await changes and I think they all look great. 

I did notice one issue in testing, which was an error "Jamf Pro Server is unavailable" when I tried an earlier version of Jamf Pro (10.21.0). This happened during the "Check Connection" button pressed.

Not sure which version cutoff it was for bearer tokens, but if you can double check how far back we want to support for Jamf Pro.

**Review by watkyn — APPROVED** [review]
Looks good!

**Pull request merged**
