### PR TITLE
Fix #79,  #54, and #83

### LINKED ISSUE #79: Properties Verbiage
"All Files" in the properties fields should be listed as "Full Disk Access", as the verbiage not being identical is rather confusing.
We even had a jamf pro member get confused by this for a minute.

### PR DESCRIPTION
**Pull request by ty-wilson**
Added to the code requirement label:
> truncates
> maximum of 2 lines
> tooltip binding
> padding on right edge

Updated All Files to Full Disk Access

### CODE REVIEW

**Comment by ty-wilson** [comment]
I noticed one small annoyance where clicking on the code requirement text field removes the truncation (...). The only way I found to prevent that is making the text field non-selectable, but I think we prefer that text field be selectable so you can highlight parts of it and copy paste.

**Comment by ty-wilson** [comment]
Added the fix for #83

**Review by hisaac — APPROVED** [review]
The UI changes look good to me!

**Comment by ty-wilson** [comment]
After a discussion with @watkyn, I opted to rename a few more properties to better reflect their counterparts under System Preferences > Security & Privacy. The MDM Key name was then added to the help text next to each property.
All Files > Full Disk Access
Address Book > Contacts
Calendar > Calendars
Listen Event > Input Monitoring
Screen Capture > Screen Recording

**Review by watkyn — APPROVED** [review]

**Pull request merged**
